// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DisneyAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210830192549_tablesup")]
    partial class tablesup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("bytea");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Models.Pelicula", b =>
                {
                    b.Property<int>("IdPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("IdGenero")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonaje")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("bytea");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("IdPelicula");

                    b.HasIndex("IdGenero");

                    b.HasIndex("IdPersonaje");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("Models.Personaje", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Historia")
                        .HasColumnType("text");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("bytea");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasKey("IdPersonaje");

                    b.HasIndex("IdPelicula");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("Models.Pelicula", b =>
                {
                    b.HasOne("Models.Genero", "genero")
                        .WithMany()
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Personaje", "personaje")
                        .WithMany()
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("genero");

                    b.Navigation("personaje");
                });

            modelBuilder.Entity("Models.Personaje", b =>
                {
                    b.HasOne("Models.Pelicula", "pelicula")
                        .WithMany()
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("pelicula");
                });
#pragma warning restore 612, 618
        }
    }
}
